name: Test Suite

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Debug Current Directory
      run: pwd

    - name: Debug Repository Files
      run: ls -R

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV  # Fix module import error

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-asyncio httpx motor pytest-cov

    - name: Run Unit Tests
      run: pytest JKTech_Bookstore/tests --cov=JKTech_Bookstore/my_bookstore --cov-report=term-missing

    - name: Run Integration Tests
      run: pytest JKTech_Bookstore/tests/integration
